### ISSUE TITLE
XBee getPanID returns error

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#247]
This XBee returns a command not supported error when requesting the PAN ID.

```
2018-03-29 15:07:19.310 [DEBUG] [ongle.xbee.internal.XBeeFrameHandler] - TX XBEE: XBeeGetPanIdCommand [frameId=16]
2018-03-29 15:07:19.310 [DEBUG] [ongle.xbee.internal.XBeeFrameHandler] - TX XBEE Data: 00 04 08 10 4F 49 4F
2018-03-29 15:07:19.432 [DEBUG] [ongle.xbee.internal.XBeeFrameHandler] - RX XBEE Data: 00 05 88 10 4F 49 02 CD
2018-03-29 15:07:19.433 [DEBUG] [ongle.xbee.internal.XBeeEventFactory] - Error creating instance of XBeeResponse
java.lang.ArrayIndexOutOfBoundsException: 8
	at com.zsmartsystems.zigbee.dongle.xbee.internal.protocol.XBeeFrame.deserializeInt16(XBeeFrame.java:93) [367:com.zsmartsystems.zigbee.dongle.xbee:1.0.8.SNAPSHOT]
	at com.zsmartsystems.zigbee.dongle.xbee.internal.protocol.XBeePanIdResponse.deserialize(XBeePanIdResponse.java:79) [367:com.zsmartsystems.zigbee.dongle.xbee:1.0.8.SNAPSHOT]
	at com.zsmartsystems.zigbee.dongle.xbee.internal.XBeeResponseFactory.getXBeeFrame(XBeeResponseFactory.java:111) [367:com.zsmartsystems.zigbee.dongle.xbee:1.0.8.SNAPSHOT]
	at com.zsmartsystems.zigbee.dongle.xbee.internal.XBeeFrameHandler$1.run(XBeeFrameHandler.java:184) [367:com.zsmartsystems.zigbee.dongle.xbee:1.0.8.SNAPSHOT]
```

First question is why, second is to avoid the exception.

**Comment by cdjackson** [comment]
The fundamental issue is the user was using the 802.15.4 firmware in the XBee and not the ZigBee firmware.
