### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid type '{com.zsmartsystems.zigbee.ZigBeeChannel}' of configuration value!

### ISSUE THREAD

**Issue by openhab-5iver** [zsmartsystems/com.zsmartsystems.zigbee#393]
OH 1348
Zigbee snapshot 2.4.0.201809041558
Zigbee libraries 1.1.1

I'm seeing this on startup, but everything appears to be functioning...

```
2018-09-04 18:50:49.702 [WARN ] [org.eclipse.smarthome.core.internal.common.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.IllegalArgumentException: Invalid type '{com.zsmartsystems.zigbee.ZigBeeChannel}' of configuration value!
        at org.eclipse.smarthome.config.core.ConfigUtil.normalizeType(ConfigUtil.java:80) ~[?:?]
        at org.eclipse.smarthome.config.core.Configuration.put(Configuration.java:86) ~[?:?]
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.initialiseZigBee(ZigBeeCoordinatorHandler.java:412) ~[?:?]
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.lambda$1(ZigBeeCoordinatorHandler.java:437) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]


2018-09-04 18:50:49.702 [DEBUG] [com.zsmartsystems.zigbee.dongle.ember.ZigBeeDongleEzsp] - EZSP dongle startup done.
2018-09-04 18:50:49.702 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - ZigBee Initialise done. channel=CHANNEL_25, PanId=19740  EPanId=3DAB5D4A2336BFDE
```

**Comment by cdjackson** [comment]
This is an issue in openHAB - I've opened an issue there.

Thanks.
