### ISSUE TITLE
NPE during EmberHandler initialization

### ISSUE THREAD

**Issue by triller-telekom** [zsmartsystems/com.zsmartsystems.zigbee#437]
If openHAB is started without a stick attached, the following call returns an empty map, leading to an NPE afterwards:

```
Map<String, Long> counters = dongle.getCounters();
```

I will provide a PR to check if the map is not empty before updating the channels.

```
2018-11-19 11:24:52.510 [WARN ] [rappedScheduledExecutorService:67   ] - Scheduled runnable ended with an exception: java.lang.NullPointerException: null
        at org.openhab.binding.zigbee.ember.handler.EmberHandler$1.run(EmberHandler.java:107)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by triller-telekom** [comment]
Wrong repo, see https://github.com/openhab/org.openhab.binding.zigbee/issues/303
