### ISSUE TITLE
NPE during discovery due node not found

### ISSUE THREAD

**Issue by cdjackson** [zsmartsystems/com.zsmartsystems.zigbee#564]
With the new transaction manager, if a node is discovered through the association node list, the node is not added to the network manager, and then the transaction manager can't create a queue. This results in an NPE during discovery.

```
22:59:33.974  DEBUG  removeTransactionListener: ZigBeeTransaction [queueTime=112, state=COMPLETE, sendCnt=1, command=IeeeAddressRequest [0/0 -> 0/0, cluster=0001, TID=00, nwkAddrOfInterest=0, requestType=1, startIndex=0]]
22:59:33.974  DEBUG  transactionListenerRemoved: 0 outstanding
22:59:33.975  DEBUG  0022A300001732BF: transactionComplete COMPLETE 0
22:59:33.975  DEBUG  RX EZSP: EzspMessageSentHandler [type=EMBER_OUTGOING_DIRECT, indexOrDestination=0, apsFrame=EmberApsFrame [profileId=0, clusterId=1, sourceEndpoint=0, destinationEndpoint=0, options=[EMBER_APS_OPTION_ENABLE_ADDRESS_DISCOVERY, EMBER_APS_OPTION_ENABLE_ROUTE_DISCOVERY, EMBER_APS_OPTION_RETRY], groupId=0, sequence=8A], messageTag=00, status=EMBER_SUCCESS, messageContents=]
22:59:33.975  DEBUG  0: NWK Discovery IeeeAddressRequest returned IeeeAddressResponse [0/0 -> 0/0, cluster=8001, TID=--, status=SUCCESS, ieeeAddrRemoteDev=0022A300001732BF, nwkAddrRemoteDev=0, startIndex=0, nwkAddrAssocDevList=[51961]]
22:59:33.975  DEBUG  0022A300001732BF: NWK Discovery add node 0
22:59:33.976  DEBUG  0022A300001732BF: Node state updated from UNKNOWN to ONLINE
22:59:33.976  DEBUG  0022A300001732BF: Node 0 update
22:59:33.977  DEBUG  0022A300001732BF: Set profile to ZigBeeTransactionProfile [maxOutstandingTransactions=2, interTransactionDelay=7600, maxRetries=2]

Node Added ZigBeeNode [state=ONLINE, IEEE=0022A300001732BF, NWK=0000, Type=UNKNOWN]
22:59:33.978  DEBUG  51961: NWK Discovery scheduling node discovery
22:59:33.978  DEBUG  51961: NWK Discovery starting node discovery
22:59:33.978  DEBUG  0: NWK Discovery ending node discovery
22:59:33.978  DEBUG  Attempt to send command with unknown destination: ZigBeeTransaction [queueTime=-, state=WAITING, sendCnt=0, command=IeeeAddressRequest [0/0 -> 51961/0, cluster=0001, TID=--, nwkAddrOfInterest=51961, requestType=1, startIndex=0]]
22:59:33.978  DEBUG  Error getting queue for ZigBeeTransaction [queueTime=-, state=WAITING, sendCnt=0, command=IeeeAddressRequest [0/0 -> 51961/0, cluster=0001, TID=--, nwkAddrOfInterest=51961, requestType=1, startIndex=0]]
22:59:33.980  ERROR  51961: NWK Discovery error during node discovery: 
java.lang.NullPointerException
	at com.zsmartsystems.zigbee.app.discovery.ZigBeeNetworkDiscoverer.getIeeeAddress(ZigBeeNetworkDiscoverer.java:351)
	at com.zsmartsystems.zigbee.app.discovery.ZigBeeNetworkDiscoverer.access$7(ZigBeeNetworkDiscoverer.java:337)
	at com.zsmartsystems.zigbee.app.discovery.ZigBeeNetworkDiscoverer$2.run(ZigBeeNetworkDiscoverer.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'll create a PR to resolve this shortly

**Comment by cdjackson** [comment]
Closed by #565
